### ISSUE TITLE
SEM computation correct?

### ISSUE THREAD

**Issue by JoKeyser** [noahhipp/wavepain#1]
Sorry for this very off-chance comment.
I was just wondering about the definition of sem() function here:

https://github.com/noahhipp/wavepain_mri/blob/170fe128989d3b6858f11f7411874b11758c2718/overall_ratings/overall_collapse_within_subject_variance.m#L50

Should this not include a square root, i.e.

```matlab
out = nanstd(in)./sqrt(sum(~isnan(in)));
```

**Comment by noahhipp** [comment]
You are absolutely correct! Thank you so much for catching that. Will be fixed in the next commit 👍

**Comment by noahhipp** [comment]
Fixed now!
